name       : haskell-hslua
version    : 0.9.5.2
release    : 3
source     :
    - https://hackage.haskell.org/package/hslua-0.9.5.2/hslua-0.9.5.2.tar.gz : 0e4d26f8a76cbfb219851f33d31417c4a3c8f193123367a0749f047103d8bbe5
license    : MIT
component  : programming.haskell
summary    : The Scripting.Lua module is a wrapper of Lua language interpreter
description: "The Scripting.Lua module is a wrapper of Lua language interpreter \n"
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions
    - haskell-fail
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
