name       : haskell-hslua
version    : 1.0.3.2
release    : 6
source     :
    - https://hackage.haskell.org/package/hslua-1.0.3.2/hslua-1.0.3.2.tar.gz : d2d40b0c143ef58d26203f34d96d4220f1a20077386e4a5216be74260b7d6ba0
license    : MIT
component  : programming.haskell
summary    : The Scripting.Lua module is a wrapper of Lua language interpreter
description: |
    The Scripting.Lua module is a wrapper of Lua language interpreter
builddeps  :
    - pkgconfig(lua-5.3)
    - haskell-base-compat-devel
    - haskell-cabal-install
    - haskell-exceptions-devel
rundeps    :
    - devel :
        - haskell-base-compat-devel
        - haskell-exceptions-devel
        - lua-devel
networking : yes
setup      : |
    sed -i "106d" hslua.cabal
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid" -fsystem-lua
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
