name       : haskell-hslua
version    : 0.5.0
release    : 1
source     :
    - https://hackage.haskell.org/package/hslua-0.5.0/hslua-0.5.0.tar.gz : 6b270a14cce6046a443e6700d0b73725bef2dc068dd40aa6a1feb1c84f41171b
license    : MIT
component  : programming.haskell
summary    : The Scripting.Lua module is a wrapper of Lua language interpreter
description: |
    The Scripting.Lua module is a wrapper of Lua language interpreter 
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
