name       : haskell-hslua
version    : 0.4.1
release    : 2
source     :
    - https://hackage.haskell.org/package/hslua-0.4.1/hslua-0.4.1.tar.gz : 2df2b4f0566ef2244506f9830e0207fce3bece7c331129f69f446c722136173f
license    : MIT
component  : programming.haskell
summary    : The Scripting.Lua module is a wrapper of Lua language interpreter
description: "The Scripting.Lua module is a wrapper of Lua language interpreter \n"
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
